### PR TITLE
Update Vapecord-Plugin.json

### PR DESCRIPTION
**Pull request by tiredcisadmin**
updated repo path

### CODE REVIEW

**Comment by SuperSaiyajinStackZ** [comment]
That's not correct. `repo` must be `<Author>/<Repo>` and not `<Author>`. It would be in that case `RedShyGuy/Vapecord-ACNL-Plugin`.

**Comment by Geezus42** [comment]
Ok, then  it should be "RedShyGuy/Vapecord-ACNL-Plugin".

**Comment by tiredcisadmin** [comment]
Ok, then I fixed it. I didn't know why LukasKeo was there.

https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/releases/download/v1.5.1/Vapecord.Public.zip

**Comment by tiredcisadmin** [comment]
Would someone mind merging this?

**Comment by SuperSaiyajinStackZ** [comment]
Merging now.

**Pull request merged**
